import type { Task } from "./columns"

export const taskData: Task[] = [
  {
    id: "8782",
    title: "Try to program without quantifying the open-source SSD",
    status: "in-progress",
    priority: "medium",
    type: "documentation",
    estimate: 8,
    createdAt: "2024-01-15",
    isUrgent: false,
  },
  {
    id: "7878",
    title: "If we parse the feed, maybe it will index the multi-byte pixel!",
    status: "backlog",
    priority: "medium",
    type: "documentation",
    estimate: 5,
    createdAt: "2024-01-12",
    isUrgent: true,
  },
  {
    id: "7839",
    title: "We need to bypass the neural firewall!",
    status: "todo",
    priority: "high",
    type: "bug",
    estimate: 12,
    createdAt: "2024-01-20",
    isUrgent: true,
  },
  {
    id: "5562",
    title: "The SAS interface is down, bypass the open-source pixel so we can back up the SMS sensor!",
    status: "backlog",
    priority: "medium",
    type: "feature",
    estimate: 16,
    createdAt: "2024-01-10",
    isUrgent: false,
  },
  {
    id: "8686",
    title: "I'll parse the wireless SSL protocol, that should driver the API panel!",
    status: "canceled",
    priority: "medium",
    type: "feature",
    estimate: 3,
    createdAt: "2024-01-08",
    isUrgent: false,
  },
  {
    id: "1280",
    title: "Use the digital TLS panel, then you can transmit the haptic system!",
    status: "done",
    priority: "high",
    type: "bug",
    estimate: 24,
    createdAt: "2024-01-25",
    isUrgent: true,
  },
  {
    id: "7262",
    title: "The UTF8 application is down, parse the neural bandwidth so we can back up the ADP array!",
    status: "done",
    priority: "high",
    type: "feature",
    estimate: 9,
    createdAt: "2024-01-22",
    isUrgent: false,
  },
  {
    id: "1138",
    title: "Generating the driver won't do anything, we need to quantify the 1080p SAS microchip!",
    status: "in-progress",
    priority: "medium",
    type: "feature",
    estimate: 7,
    createdAt: "2024-01-14",
    isUrgent: true,
  },
  {
    id: "7184",
    title: "We need to program the back-end THX pixel!",
    status: "todo",
    priority: "low",
    type: "feature",
    estimate: 4,
    createdAt: "2024-01-05",
    isUrgent: false,
  },
  {
    id: "5160",
    title: "Calculating the bus won't do anything, we need to navigate the back-end SSL protocol!",
    status: "in-progress",
    priority: "high",
    type: "documentation",
    estimate: 11,
    createdAt: "2024-01-28",
    isUrgent: true,
  },
]
